version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    labels:
      - "kind/dependencies"
    cooldown:
      default-days: 7
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    labels:
      - "kind/dependencies"
    open-pull-requests-limit: 20
    cooldown:
      default-days: 7
  - package-ecosystem: "cargo"
    directory: "/src/tests/rust_guests"
    schedule:
      interval: "daily"
      time: "03:00"
    labels:
      - "kind/dependencies"
      - "area/guest"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
