# .github/release.yml

changelog:
  categories:
    - title: Full Changelog (excl. dependencies)
      labels:
        - "*"
    - title: Full Changelog (dependencies)
      labels:
        - kind/dependencies

