# .github/release.yml

changelog:
  exclude:
    labels:
      - chore
  categories:
    - title: 🎉 New Features or Improvements
      labels:
        - kind/enhancement
    - title: 🛠 Breaking Changes 
      labels:
        - kind/breaking-change
    - title: 🐛 Bug Fixes
      labels:
        - kind/bugfix
