# .github/release.yml

changelog:
  exclude:
    labels:
      - release-notes/ignore
  categories:
    - title: New Features or Improvements
      labels:
        - kind/enhancement
    - title: Bug Fixes
      labels:
        - kind/bugfix
