# .github/release.yml

changelog:
  categories:
    - title: Full Changelog (excl. dependencies)
      labels:
        - "*"
      exclude:
        labels:
          - kind/dependencies
    - title: Full Changelog (dependencies)
      labels:
        - kind/dependencies