[build]
pre-build = [                                 
    "apt-get update && apt-get -y install gdb"
]                 

[build.env]
passthrough = [
    "TARGET_TRIPLE", # Some tests invoke Cargo directly and need this to run correctly
]