[toolchain]
channel = "1.81.0"
# if you update this, don't forget to change the pinned version
# of nightly we use in the fuzzing workflow.

targets = [ "x86_64-unknown-none", "x86_64-pc-windows-msvc" ]
