name: Release Blocker Check

on:
  workflow_call:
    inputs:
      repository:
        description: "Repository to check in format 'owner/repo'"
        required: false
        type: string
        default: ${{ github.repository }}
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository to check in format 'owner/repo'"
        required: false
        type: string

permissions:
  issues: read
  contents: read

jobs:
  check-blockers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Check for Release Blocking Issues
        run: |
          REPO="${{ inputs.repository || github.repository }}"
          echo "Checking repository: $REPO"
          
          # Only check for release blockers on release branches
          if [[ "${{ github.ref }}" == *"refs/heads/release/"* ]]; then
            echo "Release branch detected - checking for release blockers..."
            if ! ./dev/check-release-blockers.sh "$REPO"; then
              echo "::error::Release blocked by open issues with 'release-blocker' label"
              exit 1
            fi
          else
            echo "Non-release branch - skipping release blocker check"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
